name: Run tests

on:
  push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    container: fenicsproject/test-env:openmpi

    env:
      CC: clang-10
      CXX: clang++-10

      PETSC_ARCH: linux-gnu-complex-32
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none

    steps:
      - uses: actions/checkout@v2
      - name: Clone Basix
        uses: actions/checkout@v2
        with:
          path: ./basix
          repository: FEniCS/basix
          ref: main
      - name: Install Basix
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer -B build-dir -S ./basix
          cmake --build build-dir
          cmake --install build-dir
          pip3 install ./basix/python
      - name: Install UFL and FFCx
        run: |
          python3 -m pip install git+https://github.com/FEniCS/ufl.git
          python3 -m pip install git+https://github.com/FEniCS/ffcx.git
      - name: Get DOLFINx
        uses: actions/checkout@v2
        with:
          path: ./dolfinx
          repository: FEniCS/dolfinx
          ref: main

      - name: Install DOLFINx
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer -B build -S dolfinx/cpp/
          cmake --build build
          cmake --install build
          python3 -m pip -v install --global-option build --global-option --debug dolfinx/python/

      - name: Install requirements
        run: |
          python3 -m pip install sympy
      - name: Run unit tests
        run: python3 -m pytest -v test/
